version: 2.1

####### CIRCLECI COMMANDS #######

commands:
  install-gems:
    steps:
      - checkout
      - run:
          name: Install Rails & Rubocop
          command: |
            bundle install
          environment:
            BUNDLE_RETRY: 3
            BUNDLE_JOBS: 3
            BUNDLE_FROZEN: true

####### CIRCLECI JOBS #######

jobs:
  root:
    resource_class: small
    docker:
      - image: ruby:3.1.0
    steps:
      - install-gems
      - run:
          name: "Run Tests"
          command: ruby -Itest test/template/plugin/generator_test.rb && ruby -Itest test/scripts/create_component_test.rb

####### CIRCLECI WORKFLOWS #######

workflows:
  root-workflow:
    jobs:
      - root
