version: 2.1

####### YAML ANCHORS #######

attach-to-workspace: &attach-to-workspace
  attach_workspace:
    at: /root

####### CIRCLECI COMMANDS #######

commands:
  install-gems:
    steps:
      - checkout
      - run:
          name: Install Rails
          command: |
            gem install rails -v 6.1.5

####### CIRCLECI JOBS #######

jobs:
  root:
    resource_class: small
    docker:
      - image: ruby:2.7.6
    steps:
      - install-gems
      - run:
          name: "Run Tests"
          command: ruby -Itest test/template/plugin/generator_test.rb && ruby -Itest test/scripts/create_component_test.rb

####### CIRCLECI WORKFLOWS #######

workflows:
  root-workflow:
    jobs:
      - root
